### ISSUE TITLE
Main Component compile error

### ISSUE THREAD

**Issue by pasly0920** [UOS-CONNECTION/UOS-CONNECTION#10]
merge issue 해결하던 중 확인하였고 타입 설정 오류인듯 합니다
```javascript
interface IShareCard {
  data: IData,
}
```
```javascript
export interface IUser {
  id: number,
  img: string,
  name: string,
  score: number,
  short_desc: string,
}

export interface IData {
  id: number,
  title: string,
  label: string[],
  desc: string,
  User: IUser,
}
```

<img width="762" alt="제목 없음" src="https://user-images.githubusercontent.com/86864534/153337749-138bc876-8418-44c0-8050-e2db201c8a78.png">

**Comment by pasly0920** [comment]
추가적으로 interface의 경우 각 줄이 save 시에 자동으로 세미클론으로 끝나도록 포맷팅되는데 다른 분들은 어떠신지 의견 달아주시면 감사하겠습니다

**Comment by pasly0920** [comment]
상세 페이지 제작에 관한 PR의 Type에 위의 img가 추가되었는데 혹시 commit이 꼬인 걸까요?? 아니면 다른 의도인 것일까요??

**Comment by poiu694** [comment]
PR꼬인 것 같아요.....

**Comment by pasly0920** [comment]
아 ㅋㅋㅋㅋㅋ 이 친구는 이제 닫도록 하겠습니다.
