### ISSUE TITLE
[Feature] Make Page with design in Frontend

### ISSUE THREAD

**Issue by poiu694** [UOS-CONNECTION/UOS-CONNECTION#6]
Figma에서 만든 페이지대로 react + mui + scss를 이용해서 만들기

- [x] 메인 페이지
- [x] 디테일 페이지
- [x] 로그인/회원가입 페이지
- [x] 채팅 페이지
- [x] 어바웃 페이지

**Comment by pasly0920** [comment]
mui도 사용하는 거 확정인가요?? 저번에 간단히 넘어갔던 기억이 있습니다만..

**Comment by poiu694** [comment]
> _mui도 사용하는 거 확정인가요?? 저번에 간단히 넘어갔던 기억이 있습니다만.._

@pasly0920 전에 사용하자고 했던 것으로 기억합니다!

**Comment by gaeguul** [comment]
> mui도 사용하는 거 확정인가요?? 저번에 간단히 넘어갔던 기억이 있습니다만..

네! 저도 사용하는걸로 알고 있습니다!
